<template>
  <div>
    分类
    <div class="wrapper">
      <ul class="content">
        <li>呵呵哈哈哈1</li>
        <li>呵呵哈哈哈2</li>
        <li>呵呵哈哈哈3</li>
        <li>呵呵哈哈哈4</li>
        <li>呵呵哈哈哈5</li>
        <li>呵呵哈哈哈6</li>
        <li>呵呵哈哈哈7</li>
        <li>呵呵哈哈哈8</li>
        <li>呵呵哈哈哈9</li>
        <li>呵呵哈哈哈10</li>
        <li>呵呵哈哈哈11</li>
        <li>呵呵哈哈哈12</li>
        <li>呵呵哈哈哈13</li>
        <li>呵呵哈哈哈14</li>
        <li>呵呵哈哈哈15</li>
        <li>呵呵哈哈哈16</li>
        <li>呵呵哈哈哈17</li>
        <li>呵呵哈哈哈18</li>
        <li>呵呵哈哈哈19</li>
        <li>呵呵哈哈哈20</li>
        <li>呵呵哈哈哈21</li>
        <li>呵呵哈哈哈22</li>
        <li>呵呵哈哈哈23</li>
        <li>呵呵哈哈哈24</li>
        <li>呵呵哈哈哈25</li>
        <li>呵呵哈哈哈26</li>
        <li>呵呵哈哈哈27</li>
        <li>呵呵哈哈哈28</li>
        <li>呵呵哈哈哈29</li>
        <li>呵呵哈哈哈30</li>
        <li>呵呵哈哈哈31</li>
        <li>呵呵哈哈哈32</li>
        <li>呵呵哈哈哈33</li>
        <li>呵呵哈哈哈34</li>
        <li>呵呵哈哈哈35</li>
        <li>呵呵哈哈哈36</li>
        <li>呵呵哈哈哈37</li>
        <li>呵呵哈哈哈38</li>
        <li>呵呵哈哈哈39</li>
        <li>呵呵哈哈哈40</li>
        <li>呵呵哈哈哈41</li>
        <li>呵呵哈哈哈42</li>
        <li>呵呵哈哈哈43</li>
        <li>呵呵哈哈哈44</li>
        <li>呵呵哈哈哈45</li>
        <li>呵呵哈哈哈46</li>
        <li>呵呵哈哈哈47</li>
        <li>呵呵哈哈哈48</li>
        <li>呵呵哈哈哈49</li>
        <li>呵呵哈哈哈50</li>
        <li>呵呵哈哈哈51</li>
        <li>呵呵哈哈哈52</li>
        <li>呵呵哈哈哈53</li>
        <li>呵呵哈哈哈54</li>
        <li>呵呵哈哈哈55</li>
        <li>呵呵哈哈哈56</li>
        <li>呵呵哈哈哈57</li>
        <li>呵呵哈哈哈58</li>
        <li>呵呵哈哈哈59</li>
        <li>呵呵哈哈哈60</li>
        <li>呵呵哈哈哈61</li>
        <li>呵呵哈哈哈62</li>
        <li>呵呵哈哈哈63</li>
        <li>呵呵哈哈哈64</li>
        <li>呵呵哈哈哈65</li>
        <li>呵呵哈哈哈66</li>
        <li>呵呵哈哈哈67</li>
        <li>呵呵哈哈哈68</li>
        <li>呵呵哈哈哈69</li>
        <li>呵呵哈哈哈70</li>
        <li>呵呵哈哈哈71</li>
        <li>呵呵哈哈哈72</li>
        <li>呵呵哈哈哈73</li>
        <li>呵呵哈哈哈74</li>
        <li>呵呵哈哈哈75</li>
        <li>呵呵哈哈哈76</li>
        <li>呵呵哈哈哈77</li>
        <li>呵呵哈哈哈78</li>
        <li>呵呵哈哈哈79</li>
        <li>呵呵哈哈哈80</li>
        <li>呵呵哈哈哈81</li>
        <li>呵呵哈哈哈82</li>
        <li>呵呵哈哈哈83</li>
        <li>呵呵哈哈哈84</li>
        <li>呵呵哈哈哈85</li>
        <li>呵呵哈哈哈86</li>
        <li>呵呵哈哈哈87</li>
        <li>呵呵哈哈哈88</li>
        <li>呵呵哈哈哈89</li>
        <li>呵呵哈哈哈90</li>
        <li>呵呵哈哈哈91</li>
        <li>呵呵哈哈哈92</li>
        <li>呵呵哈哈哈93</li>
        <li>呵呵哈哈哈94</li>
        <li>呵呵哈哈哈95</li>
        <li>呵呵哈哈哈96</li>
        <li>呵呵哈哈哈97</li>
        <li>呵呵哈哈哈98</li>
        <li>呵呵哈哈哈99</li>
        <li>呵呵哈哈哈100</li>
        <li>分类的列表1</li>
        <li>分类的列表2</li>
        <li>分类的列表3</li>
        <li>分类的列表4</li>
        <li>分类的列表5</li>
        <li>分类的列表6</li>
        <li>分类的列表7</li>
        <li>分类的列表8</li>
        <li>分类的列表9</li>
        <li>分类的列表10</li>
        <li>分类的列表11</li>
        <li>分类的列表12</li>
        <li>分类的列表13</li>
        <li>分类的列表14</li>
        <li>分类的列表15</li>
        <li>分类的列表16</li>
        <li>分类的列表17</li>
        <li>分类的列表18</li>
        <li>分类的列表19</li>
        <li>分类的列表20</li>
        <li>分类的列表21</li>
        <li>分类的列表22</li>
        <li>分类的列表23</li>
        <li>分类的列表24</li>
        <li>分类的列表25</li>
        <li>分类的列表26</li>
        <li>分类的列表27</li>
        <li>分类的列表28</li>
        <li>分类的列表29</li>
        <li>分类的列表30</li>
        <li>分类的列表31</li>
        <li>分类的列表32</li>
        <li>分类的列表33</li>
        <li>分类的列表34</li>
        <li>分类的列表35</li>
        <li>分类的列表36</li>
        <li>分类的列表37</li>
        <li>分类的列表38</li>
        <li>分类的列表39</li>
        <li>分类的列表40</li>
        <li>分类的列表41</li>
        <li>分类的列表42</li>
        <li>分类的列表43</li>
        <li>分类的列表44</li>
        <li>分类的列表45</li>
        <li>分类的列表46</li>
        <li>分类的列表47</li>
        <li>分类的列表48</li>
        <li>分类的列表49</li>
        <li>分类的列表50</li>
        <li>分类的列表51</li>
        <li>分类的列表52</li>
        <li>分类的列表53</li>
        <li>分类的列表54</li>
        <li>分类的列表55</li>
        <li>分类的列表56</li>
        <li>分类的列表57</li>
        <li>分类的列表58</li>
        <li>分类的列表59</li>
        <li>分类的列表60</li>
        <li>分类的列表61</li>
        <li>分类的列表62</li>
        <li>分类的列表63</li>
        <li>分类的列表64</li>
        <li>分类的列表65</li>
        <li>分类的列表66</li>
        <li>分类的列表67</li>
        <li>分类的列表68</li>
        <li>分类的列表69</li>
        <li>分类的列表70</li>
        <li>分类的列表71</li>
        <li>分类的列表72</li>
        <li>分类的列表73</li>
        <li>分类的列表74</li>
        <li>分类的列表75</li>
        <li>分类的列表76</li>
        <li>分类的列表77</li>
        <li>分类的列表78</li>
        <li>分类的列表79</li>
        <li>分类的列表80</li>
        <li>分类的列表81</li>
        <li>分类的列表82</li>
        <li>分类的列表83</li>
        <li>分类的列表84</li>
        <li>分类的列表85</li>
        <li>分类的列表86</li>
        <li>分类的列表87</li>
        <li>分类的列表88</li>
        <li>分类的列表89</li>
        <li>分类的列表90</li>
        <li>分类的列表91</li>
        <li>分类的列表92</li>
        <li>分类的列表93</li>
        <li>分类的列表94</li>
        <li>分类的列表95</li>
        <li>分类的列表96</li>
        <li>分类的列表97</li>
        <li>分类的列表98</li>
        <li>分类的列表99</li>
        <li>分类的列表100</li>
      </ul>
    </div>
  </div>
</template>

<script>
import BScroll from "@better-scroll/core";

export default {
  data() {
    return {
      scroll: null
    };
  },
  mounted() {
    this.scroll = new BScroll(".wrapper", {
      // scrollY: true,
      // click: true,
      probeType: 3
    });
    function onScroll(pos) {
      console.log(`Now position is x: ${pos.x}, y: ${pos.y}`);
    }
    this.scroll.on("scroll", onScroll);
  }
};
</script>

<style scoped>
.wrapper {
  height: 150px;
  background-color: deeppink;
}
</style>